apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0   # Specify version instead of 'latest' for better control
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "rootpassword"  # Static root password
        - name: MYSQL_DATABASE
          value: "wikidb"        # Database to be used by Wiki.js
        - name: MYSQL_USER
          value: "wikiuser"      # Wiki.js user
        - name: MYSQL_PASSWORD
          value: "wikipassword"  # Wiki.js user password
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
